#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tflearn
Version  : 0.2.2
Release  : 2
URL      : https://pypi.python.org/packages/a1/f3/01770ba6242f8e5e557247597843c2a6cb645d46ae430b99756cd580270c/tflearn0.2.2.tar.gz
Source0  : https://pypi.python.org/packages/a1/f3/01770ba6242f8e5e557247597843c2a6cb645d46ae430b99756cd580270c/tflearn0.2.2.tar.gz
Summary  : Deep Learning Library featuring a higher-level API for Tensorflow
Group    : Development/Tools
License  : MIT
Requires: tflearn-python
BuildRequires : Pillow
BuildRequires : numpy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
No detailed description available

%package python
Summary: python components for the tflearn package.
Group: Default

%description python
python components for the tflearn package.


%prep
%setup -q -n 0.2.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1486267951
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1486267951
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
